language: python
python: '2.7'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- virtualenv buildout
- mkdir -p buildout-cache/downloads
- buildout/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- make html
after_script:
- travis-artifacts upload --path build/html
env:
  global:
  - ARTIFACTS_S3_BUCKET=plone-papyrus
  - secure: ChSaA0uAtrvf7OnKApr/SyWxVoHhO+yC9tT97uEscsGpRjLNYE2NXpUg8fuLjFVX+jfwfOy4UfrruzEzctnlgGuo0bNF4PBoR7fS2DSzeiYlMkFLkp0fsGvJtCOBy2ENX52sJj9KMONjtczMeBRPnMKWiPcZBBYRd9HUsb7fhv4=
  - secure: Y43rO/1QR1AKsZYVu0Vz/O42m2tekcWLn/BUZL2KP4WX83QDliaPwkR4WEVEGqzEDfGpcsXvTRNhc9it0YWAld7GJj/NjAtBGIBdy+RXOG+Y51O7aplfu8ozhS5xpkDyg/GP5lib5rA5XrlZuLJ0gPBrJKzRICdI//7Qbus+gg8=
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Sphinx: http://plone-papyrus.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/en/'
