language: python
python:
- 2.7
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- python bootstrap-buildout.py
- bin/buildout -N -t 3
script:
- make html
cache:
  directories:
  - eggs
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
