language: python
python:
- 2.7
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -O http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz
- tar xzvf enchant-1.6.0.tar.gz
- cd enchant-1.6.0
- ./configure --prefix=`pwd`
- make install
- cd ..
install:
- python bootstrap-buildout.py
- bin/buildout -N -t 3
script:
- make html
cache:
  directories:
  - eggs
env:
  global:
  - LD_LIBRARY_PATH=`pwd`/enchant-1.6.0/lib
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
