language: python
python: '2.7'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- virtualenv buildout
- mkdir -p buildout-cache/downloads
- buildout/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
script:
- make html
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
